### PR TITLE
0000 progress to id 60/readme.md additions and fixes

### PR DESCRIPTION
**Pull request by rustyJS**
won't automatically merge atm, will fix soon

### CODE REVIEW

**Comment by rustyMB** [comment]
merge situation resolved

**Comment by rustyJS** [comment]
im not really sure what to change in the readme

**Comment by noneucat** [comment]
There shouldn't be any commits affecting the README if this is strictly script work.

**Comment by rustyJS** [comment]
no i mean like the readme conflict im not sure what to do with that one

**Comment by rustyJS** [comment]
if i were to remove the file it'd remove it when it merges, so this pull request is also for giving the `README.md` some more information i guess

**Comment by noneucat** [comment]
Please try not to mix changes in PRs; open a separate PR for the proposed README changes and file additions. 

Refer to https://stackoverflow.com/questions/39459467/remove-a-modified-file-from-pull-request for instructions on removing changes from the PR.

**Pull request closed without merging**
